server:
  port: 8080

spring:
  profiles:
    active: local

  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL

    session:
      store-type: jdbc